# Generated by Django 5.2.6 on 2025-09-28 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.supplier",
            ),
        ),
    ]
