# Generated by Django 5.2.6 on 2025-09-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_invoice_supplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="hours",
        ),
    ]
