# Generated by Django 5.2.6 on 2025-09-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_invoice_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="hours",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
